### ISSUE TITLE
Chapter 4: Column types does not include missing after reading them with CSV

### ISSUE THREAD

**Issue by KristofferC** [bkamins/Julia-DataFrames-Tutorial#24]
![bild](https://user-images.githubusercontent.com/1282691/82896891-03074280-9f57-11ea-8cd1-2f2f576c5fdd.png)

One column type changed `String` -> `Char` but the first column is still only of type `Bool`.

**Comment by bkamins** [comment]
Ah - thank you for noting this. This part of the tutorials was written a long time ago, and things have changed in some places. I will review them.

**Comment by bkamins** [comment]
Fixed. Also fixed CSVFiles.jl.
