### ISSUE TITLE
JDF dependency errored

### ISSUE THREAD

**Issue by pjgoodall** [bkamins/Julia-DataFrames-Tutorial#33]
julia version :  1.6.2 (2021-07-14)

```
Precompiling project...
  ✗ JDF
  125 dependencies successfully precompiled in 76 seconds (71 already precompiled)
  1 dependency errored. To see a full report either run `import Pkg; Pkg.precompile()` or load the package
```

I've only been using Julia for a bit over a week, so not sure where to go from here. Happy to answer questions...

**Comment by bkamins** [comment]
Hi,

1. I have checked and cannot reproduce this problem.
2. Can you please report what happens if you try do `using JDF` after starting `julia` and activating the project.
3. I assume you made sure to use the latest version of the tutorial. Can you please double check this.
4. Before the problem is resolved - it only affects Notebook 4, all other notebooks will work.

Thank you!

**Comment by pjgoodall** [comment]
I first noticed it on my on my Ubuntu 20.04 workstation. Here I am trying to reproduce it within a clean install on an LXC ubuntu 20.04 container created with access to NVIDIA hardware pass-through.

I could not reproduce the problem in the container environment.
I then went back to my host workstation, cloned the tutorial code again, and ran the initialisation
`julia -e 'using Pkg; Pkg.activate("."); Pkg.instantiate()'`

```
pkg> activate .
  Activating environment at `~/Tutorials/Julia-Tutorials/Julia-DataFrames-Tutorial/Project.toml`

julia> using JDF

julia> 

```

No problem.

I tried update from the package manager, and the problem appeared.  I don't remember doing that - but that must be what I did. My apologies for wasting your time !

 

## LXC container test

```
% lxc launch -e ubuntu:20.04 --profile default --profile nvidia-cuda Julia-Dataframes-Tutorial
Creating Julia-Dataframes-Tutorial
Starting Julia-Dataframes-Tutorial
```
login to container:

```
% export c1=Julia-Dataframes-Tutorial 
% lxc exec $c1 -- su --login ubuntu                                                           
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.
```
Install Julia:
```
% wget https://julialang-s3.julialang.org/bin/linux/x64/1.6/julia-1.6.2-linux-x86_64.tar.gz
[...]
% tar zxvf julia-1.6.2-linux-x86_64.tar.gz
[...]
$ alias julia='~/julia-1.6.2/bin/julia'
$ julia --version
julia version 1.6.2
```

clone and instantiate tutorial
```
$ git clone https://github.com/bkamins/Julia-DataFrames-Tutorial.git
Cloning into 'Julia-DataFrames-Tutorial'...
remote: Enumerating objects: 661, done.
remote: Counting objects: 100% (118/118), done.
remote: Compressing objects: 100% (66/66), done.
remote: Total 661 (delta 86), reused 78 (delta 52), pack-reused 543
Receiving objects: 100% (661/661), 4.73 MiB | 3.49 MiB/s, done.
Resolving deltas: 100% (489/489), done.

$ julia -e 'using Pkg; Pkg.activate("."); Pkg.instantiate()'
[...]
Precompiling project...
  189 dependencies successfully precompiled in 114 seconds (8 already precompiled)

```

No problem in container






```
