### ISSUE TITLE
Custom index type

### ISSUE THREAD

**Issue by juliohm** [bkamins/Julia-DataFrames-Tutorial#4]
Given a dataset like:

```
	Fat	Sodium	Carbonates Protein  total
soy	  7	    14	        10	13    100
peas	  3	    12	        61	22    100
wheat	  1	    15	        60	23    100
corn	  1	   180	        15	 2     82
beans	  0.5	   680          30	12     NA

```

How to load it so that the first column is interpreted as the index column, and how to manipulate the resulting dataframe? Is this possible with the current state of DataFrames.jl?

**Comment by bkamins** [comment]
If you want the first column to be a true index (not a normal column) then currently it is not possible currently in `DataFrames` (but there are discussions about it).
You should rather use https://github.com/JuliaComputing/IndexedTables.jl for that.

The other issue is fixed-width-fields which you probably have to parse manually, but this should be pretty simple (I am not aware of any standard package for this - all concentrate on CSV type sources).

**Comment by juliohm** [comment]
Thank you @bkamins , I am closing this one for now.

**Comment by bkamins** [comment]
I have written a simple parser for FWF files here https://github.com/bkamins/FWF.jl. It is a WIP.
