### ISSUE TITLE
Converting Dataframe row to raw Julia vector?

### ISSUE THREAD

**Issue by juliohm** [bkamins/Julia-DataFrames-Tutorial#5]
Could you please add an example to the `rows` tutorial explaining how users can convert DataFrame rows into Julia vectors or arrays?

I was used to doing `vec(convert(Array, df[row,cols]))`, but this doesn't work anymore because of the introduction of Missing Unions.

**Comment by bkamins** [comment]
I have checked it and it works on both 0.6.2 and 0.7. Can you give an example when it fails?
The only problem is that `Array(df[row, cols])` worked on 0.6.2 and fails on 0.7. I will have to have a look at it.

On the other hand you can always write `[df[row,col] for col in cols]` which is explicit, not so long and should be faster than `convert`. I could add this as a recommendation - what do you think?

**Comment by juliohm** [comment]
The list comprehension solution works perfectly and throws away the
annoying Missing type. That would be great to have in the tutorials,
thanks!

**Comment by bkamins** [comment]
Fixed (it took some time as I had to fix a bug in *DataFrames.jl* to make this workbook work properly).

**Comment by juliohm** [comment]
Thank you @bkamins for your help and work. Closing the issue.
